students/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from st_and_gr.views import Start,Registration,Groups_List,Create_Group,Edit_Group,Students_List,Add_Student,Edit_Student,Settings_List,now_used_group,Edit_Headman,now_used_headman

from django.contrib import admin
admin.autodiscover()
urlpatterns = patterns('',
     
     url(r'^$',Start.as_view(), name='start'),
     url(r'^registration/$',Registration.as_view(), name='registration'),
     url(r'^settings_list/$',Settings_List.as_view(), name='settings_list'),
     url(r'^logout/$','st_and_gr.views.logout', name='logout'),
#________________________________
     url(r'^groups_list/$',Groups_List.as_view(), name='groups_list'),     
     url(r'^group/create/$',Create_Group.as_view(), name='create_group'),
     url(r'^group/(?P<pk>\d+)/now_used_group/$','st_and_gr.views.now_used_group', name='now_used_group'),
     url(r'^group/(?P<pk>\d+)/edit/$',Edit_Group.as_view(), name='edit_group'),
     url(r'^group/(?P<pk_group>\d+)/del/$','st_and_gr.views.del_group', name='del_group'),
#________________________________     
     url(r'^list_of_students_for_the_group/(?P<pk_group>\d+)/$', Students_List.as_view(), name='students_list'),
     url(r'^student/add/$',Add_Student.as_view(), name='add_student'),
     
     url(r'^student/(?P<pk>\d+)/group/(?P<pk_group_edit>\d+)/now_used_headman/$','st_and_gr.views.now_used_headman', name='now_used_headman'),
     url(r'^headman/(?P<pk>\d+)/group/(?P<pk_group_edit>\d+)/edit/$', Edit_Headman.as_view(), name='edit_headman'),
     url(r'^student/(?P<pk>\d+)/group/(?P<pk_group_edit>\d+)/edit/$', Edit_Student.as_view(), name='edit_student'),
      
     url(r'^student/(?P<pk_student>\d+)/group/(?P<pk_group_del>\d+)/del/$','st_and_gr.views.del_student', name='del_student'),
#________________________________      
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
     url(r'^admin/', include(admin.site.urls))
                       )
if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

st_and_gr/models.py
# coding: utf-8
from django.db import models
from django.forms import ModelForm
from django.db.models.signals import post_init, post_save, post_delete
from django.dispatch import receiver
from datetime import datetime

class Info_About_Models(models.Model):  
    model_name=models.CharField(max_length=255,verbose_name=u'Имя модели')
    model_create=models.CharField(max_length=255,verbose_name=u'Информация о создании новой записи в модель')
    model_editing=models.CharField(max_length=255,verbose_name=u'Информация о редактировании модели')  
    model_delete=models.CharField(max_length=255,verbose_name=u'Информация об удалении записи из модели')
    class Meta:
        verbose_name_plural = "Информация о моделях"

    def __unicode__(self):
        return self.model_name 
       
class Students(models.Model):
    full_name = models.CharField(max_length=300, verbose_name=u'Полное имя')
    date_of_birth = models.CharField(max_length=300,verbose_name=u'Дата рождения')
    student_id_number=models.IntegerField(default=0,verbose_name=u'Номер студ. билета ')
    group=models.ForeignKey('Groups',verbose_name=u'Группа, к которой прикреплен студент')
    class Meta:
        verbose_name_plural = "Студенты"
        
    def __unicode__(self):
        return self.full_name
        
class Groups(models.Model):
    group_name=models.CharField(max_length=300,verbose_name=u'Название группы')
    headman=models.ForeignKey(Students,verbose_name=u'Староста')  
    now_used=models.BooleanField(default=False) #поле используется при редактировании группы(инф.о том, какая группа сейчас редактируется)
 
    class Meta:
        verbose_name_plural = "Группы"

    def __unicode__(self):
        return self.group_name    

@receiver(post_init, sender = Students) # создание новой записи (модель Students)
def post_init_students(instance, **kwargs):
    i_a_m=Info_About_Models.objects.get(model_name='Students') 
    i_a_m.model_create=datetime.now()
    i_a_m.save()

@receiver(post_save, sender = Students) # редактирование записи (модель Students)
def post_save_students(instance, **kwargs):
    i_a_m=Info_About_Models.objects.get(model_name='Students') 
    i_a_m.model_editing=datetime.now()
    i_a_m.save()

@receiver(post_delete, sender = Students) #  удаление записи (модель Students)
def post_delete_students(instance, **kwargs):
    i_a_m=Info_About_Models.objects.get(model_name='Students') 
    i_a_m.model_delete=datetime.now()
    i_a_m.save()

@receiver(post_init, sender = Groups) # создание новой записи (модель Groups)
def post_init_groups(instance, **kwargs):
    i_a_m=Info_About_Models.objects.get(model_name='Groups') 
    i_a_m.model_create=datetime.now()
    i_a_m.save()

@receiver(post_save, sender = Groups) # редактирование записи (модель Groups)
def post_save_groups(instance, **kwargs):
    i_a_m=Info_About_Models.objects.get(model_name='Groups') 
    i_a_m.model_editing=datetime.now()
    i_a_m.save()

@receiver(post_delete, sender = Groups) # удаление записи (модель Groups)
def post_delete_groups(instance, **kwargs):
    i_a_m=Info_About_Models.objects.get(model_name='Groups') 
    i_a_m.model_delete=datetime.now()
    i_a_m.save()
    
       

    

students/templates/add_student.html
{% extends 'base.html' %}

{% block title %}
Создать учётную запись студента
{% endblock %}
{% block content %}
<div align="center">
<br>
<br>
<h1>Создать учётную запись студента</h1>

<!-------------------------->
<div class="pad_center">

{% if form.errors %}
<p style="color: red;">
Пожалуйста, исправьте ошибки  
</p>
{% endif %}

<form action="" method="post">  {% csrf_token %}
<div style="padding-right:260px">
<table>
{{ form.as_table }}
</table>
</div>
<div class="btn_position"> <input type="submit"  class="btn btn-primary" value="Создать"></div>
</form>
 
</div>
<!-------------------------->
</div>

{% endblock %}

students/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8" />

<title>
{% block title%}
Система учета студентов 
{% endblock %}
</title>

<link href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="{{STATIC_URL}}bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
<link href="{{STATIC_URL}}bootstrap/css/new1.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

<style>
body {background:#d5c6b5;
padding-top: 80px; 
}
</style>

</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">
<div class="container" >

<div class="brand" >
<a href="{% url 'start' %}"> На главную </a>
</div>
<!------------------------------------------------------>
<div align="right" style="padding-top:7px" >

<form class="form-inline">
{% if user.is_authenticated %}
<input type="button" name="Список групп" " class="btn btn-inverse" onclick="location.href='{%url 'groups_list'%}'"  value="Список групп">

<input type="button" name="Список настроек проекта" " class="btn btn-inverse" onclick="location.href='{%url 'settings_list'%}'"  value="Список настроек проекта">
<input type="button" name="Выйти"  class="btn btn-inverse" onclick="location.href='{%url 'logout'%}'" value="Выйти">
{% else %}
<input type="button" name="Регистрация" " class="btn btn-inverse" onclick="location.href='{%url 'registration'%}'"  value="Регистрация">

{% endif %}
</form>

</div>
<!---------------------------------------------------------->

</div>
</div>
</div>
<!-------------------------------------->
<div class="container" style="margin-bottom:100px"  align="center">
{% if user.is_authenticated %}
<div class="row">

<div class="span4" >
<div align="left"><p>Вы зашли как {{ user.username }}</p> </div>
</div>

</div>
<!----------->

{% else %}
<div align="left">
<p>Вы не зашли в систему </p>
</div>
{% endif %}

<!-------------------------------------->
{% block content %}

{% endblock %}

<!--  end container -->
</div>
<!-------------------------------------------->

<div  class="navbar navbar-fixed-bottom">
<div class="navbar-inner" style="background: rgba(114, 111, 108, 0.8);">

<div class="container">
Система учета студентов
</div>

</div>
</div>
<!-------------------------------------------->
</body>
</html>

students/templates/create_group.html
{% extends 'base.html' %}

{% block title %}
Создать группу
{% endblock %}
<!-------------------------------------------------->
{% block content %}
<div align="center">
<br>
<br>
<h1>Создать группу</h1>

<!-------------------------->
<div class="pad_center">

{% if form.errors %}
<p style="color: red;">
Пожалуйста, исправьте ошибки  
</p>
{% endif %}

<form action="" method="post">  {% csrf_token %}
<div style="padding-right:120px">
<table>
{{ form.as_table }}
</table>
</div>
<div class="btn_position"> <input type="submit"  class="btn btn-primary" value="Создать группу"></div>
</form>
 
</div>
<!-------------------------->
</div>
<!-------------------------------------------------->
<br>

<div align="left">
<h5>

После того, как в этой группе<br> 
появятся  студенты - будет возможно <br>
назначить старосту из них.  
</h5>
</div>

{% endblock %}

students/templates/edit_group.html
{% extends 'base.html' %}

{% block title %}
Редактировать группу
{% endblock %}

{% block content %}
<div class=" row">
<!----------------------------------------->
<div class="span7">
<br>
<br>
<h1>Редактировать группу  "{{group.group_name }}"</h1>

<!-------------------------->
<div class="pad_center">

{% if form.errors %}
<p style="color: red;">
Пожалуйста, исправьте ошибки  
</p>
{% endif %}

<form action="" method="post">  {% csrf_token %}

<div style="padding-right:110px">
<table>
{{ form.as_table }}
</table>
</div>
<div class="btn_position"> <input type="submit"  class="btn btn-primary" value="Сохранить изменения"></div>
</form>
 
</div>

<!-------------------------->
</div>
<!----------------------------------------->
<div class="span5">
<div align="left" style="padding-left:20%">
<br>
<br>
<br>
{% if group_students.count > 0 %}
<h4>Список студентов этой группы:</h4>

<h5>
<ul>
{% for student in group_students %}

<li> {{student.full_name}}  </li>

{% endfor %}
</ul>
</h5>
 
</div>
{%else%}
<!--------------------------------->
<div align="left" style="padding-left:20%">
<br>

<h4>
В этой группе нет студентов
</h4>
 </div>
<!--------------------------------->
{% endif %}

</div>
<!----------------------------->
</div>
{% endblock %}

students/templates/edit_headman.html
{% extends 'base.html' %}

{% block title %}
Редактировать учётную запись студента
{% endblock %}

{% block content %}
<div align="center">
<br>
<br>
<h1>Редактировать учётную запись старосты</h1>

<!-------------------------->
<div class="pad_center">

{% if form.errors %}
<p style="color: red;">
Пожалуйста, исправьте ошибки  
</p>
{% endif %}

<div style="padding-right:140px ">
<form action="" method="post">  {% csrf_token %}
<table>
{{ form.as_table }}
</table>
</div>
<div class="btn_position"> <input type="submit"  class="btn btn-primary" value="Сохранить"></div>
</form>
 
</div>
<!-------------------------->
</div>

<div align="left">
<h5>
Поскольку этот студент - староста,<br>
для перевода его в другую группу, <br>
переопределите старосту в его группе.
</h5>
</div>
{% endblock %}

students/templates/edit_student.html
{% extends 'base.html' %}

{% block title %}
Редактировать учётную запись студента
{% endblock %}

{% block content %}
<div align="center">
<br>
<br>
<h1>Редактировать учётную запись студента</h1>

<!-------------------------->
<div class="pad_center">

{% if form.errors %}
<p style="color: red;">
Пожалуйста, исправьте ошибки  
</p>
{% endif %}

<div style="padding-right:260px ">
<form action="" method="post">  {% csrf_token %}
<table>
{{ form.as_table }}
</table>
</div>
<div class="btn_position"> <input type="submit"  class="btn btn-primary" value="Сохранить"></div>
</form>
 
</div>
<!-------------------------->
</div>

{% endblock %}

students/templates/groups_list.html
{% extends 'base.html' %}

{% block title %}
Список групп
{% endblock %}

{% block content %}

<br>
<br>
<h1>Список групп</h1>
<br>
<!-------------------------->
<div class="pad_center">
<table class="table">

<tr>
<td>Название группы</td>
<td>Староста</td>
<td>Количество студентов в группе</td>

<td> </td>
<td> </td>
</tr>

{% for group in groups_list %}
<tr>

<td>
{% if group.students_set.count == 0 %}
{{ group.group_name }}   
{%else%}
<a href="{% url 'students_list' pk_group=group.id %}">{{ group.group_name }} </a>
{%endif%}
</td> 


<td>
{% if group.students_set.count == 0 %}
Старосты пока что нет  
{%else%}
{{ group.headman }}
{%endif%}
</td>

<td> {{ group.students_set.count }} </td>

<td> 
{% if  group.students_set.count > 0 %}
<input type="button"
name="Редактировать" 
class="btn btn-inverse btn-small"
onclick="location.href='{% url 'now_used_group' pk=group.id %}'"
   
value="Редактировать"> 
{% else %}
<div style="padding-left:5px">
 Редактировать
</div> 
{% endif %}

</td>

<td>
<!----------------->
{% if groups_list.count == 1 %}

{%else%}
<input type="button"
name="Удалить" 
class="btn btn-inverse btn-small"
onclick="location.href='{% url 'del_group' pk_group=group.id %}'"
value="Удалить"> 
{%endif%}
<!----------------->
</td>

</tr>
{% endfor %}
</table>

<br>
<input type="button"
name="Создать группу" 
class="btn btn-success"
onclick="location.href='{% url 'create_group'%}'"
value="Создать группу"> 

<input type="button"
name="Добавить студента" 
class="btn btn-success"
onclick="location.href='{% url 'add_student'%}'"
value="Добавить студента"> 
</div>
<!-------------------------->
<br>
{% for group in groups_list %}
{% if group.students_set.count == 0 %}
{% ifchanged group.students_set.count %}
<div align="left"> 
<h5>
В группе обязательно должно быть <br>
определенное количество студентов.<br>
Добавьте хотя бы одного студента в группу,<br>
чтобы ссылки на детальное описание<br> 
и редактирование группы стали активными.  
</h5>
</div>
{% endifchanged %}
{%endif%}
{% endfor %}
<!-------------------------->
<div align="left" >
<h5>
{% if groups_list.count == 1 %}
В картотеке осталась всего одна группа.<br>
Поэтому невозможно ее удалить,<br>
поскольку в ином случае <br>
картотека будет полностью закрыта.
{%endif%}
 </h5>
</div>
<!-------------------------->
{% endblock %}

students/templates/registration.html
{% extends 'base.html' %}

{% block title %}
Регистрация
{% endblock %}

{% block content %}
<div align="center">
<br>
<br>
<h1>Регистрация</h1>
<!------------------>
<div class="pad_center">

{% if form.errors %}
<p style="color: red;">
Пожалуйста, исправьте ошибки
</p>
{% endif %}

<form action="" method="post">  {% csrf_token %}

<div style="padding-right:50px">
<table>
{{ form.as_table }}
</table>
</div>

<div class="btn_position"> <input type="submit"  class="btn btn-primary" value="Регистрация"></div>
</form>

</div>

</div>
<!------------------>
{% endblock %}

students/templates/settings_list.html
{% extends 'base.html' %}
{% load edit_object %} 


{% block title %}
Список некоторых настроек проекта
{% endblock %}

{% block content %}

<div align="center">
<br>
<br>
<h3> Список некоторых настроек проекта</h3>
<!------------------>
<div class="pad_center">

DEBUG: {{ MY_SETTINGS.DEBUG }}
<br>
<br>
TIME_ZONE:{{ MY_SETTINGS.TIME_ZONE }} 
<br>
<br>
DATABASES: {{ MY_SETTINGS.DATABASES }} 
<br>
<br>

STATIC_ROOT:{{ MY_SETTINGS.STATIC_ROOT }} 

</div>

<br>
<br> 
<h5>Работа своего шаблонного тега "edit":</h5> 

Сcылка на редактирование объекта Students: {% edit obj='Students' %}
<br>
<br>                      
Сcылка на редактирование экземпляра класса (модели) Students: {% edit obj='Students' obj_id=2 %}
<br>
<br>
Сcылка на редактирование текущего пользователя (дополнительно  передаем его id):  {% edit user=request.user obj_id=1 %}
<br>
<br>
Сcылка на редактирование текущего пользователя (id не передаем):{% edit user=request.user %}

<br>
<br>
Ошибка в использовании тега - задано больше одного объекта для формирования ссылки:  {% edit user=request.user obj='Students' %}

<br>
<br>
Ошибка в использовании тега - задано слишком много параметров : {% edit user=request.user obj='Students' obj_id=1 %}

</div>                    


{% endblock %}

students/templates/start.html
{% extends 'base.html' %}
{% block title %}
Вход в систему
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<br>
<h5 style="padding-top:80px ">
На данный момент вы вошли в систему как {{ user.username }} <br><br>
Вы можете   создавать/редактировать/удалять  информацию о группах и студентах.<br><br>
Также вы имеете возможность просматривать техническую информацию о настройках и работе сайта.<br><br>
Для дальнейшего использования сервиса воспользуйтесь верхней меню-панелью. 
</h5>
{% else %}
<!------------------------------------------->
<div align="center">
<br>
<br>
<h1>Вход в систему</h1>
<!------------------>
<div class="pad_center" >
<h4> {{error_start}} </h4>

{% if form.errors %}
<p style="color: red;">
Пожалуйста, исправьте ошибки  
</p>
{% endif %}

<form action="" method="post">  {% csrf_token %}

<div style="padding-right:80px">
<table>
{{ form.as_table }}
</table>
</div>
<div class="btn_position" > <input type="submit"  class="btn btn-primary" value="Вход"></div>
</form>

</div>
<!------------------>
</div>
<!------------------------------------------->
 {% endif %}
{% endblock %}



students/templates/students_list.html
{% extends 'base.html' %}

{% block title %}
Список  студентов из группы "{{ group.group_name }}"
{% endblock %}

{% block content %}
<br>
<br>
<h1>Список студентов из группы "{{ group.group_name }}" </h1>
               
<!-------------------------->
<div class="pad_center">
<table class="table" align="center">
<tr>
<td>Полное имя</td>
<td>Дата рождения</td>
<td>номер студ. билета</td>
<td> </td>
</tr>

<tr>
{% for student in students_list %}

<td>
<a href="{% url 'now_used_headman' pk=student.id pk_group_edit=group.id %}">{{student.full_name}} </a>
</td>

<td>{{student.date_of_birth}} </td>
<td>{{student.student_id_number}} </td>

<td>
<!-------------------------------->
{%if students_list.count > 1 and student.id == headman_id %}
<input type="button"
name="Староста" 
class="btn btn-warning btn-small"
onclick="location.href='{% url 'now_used_group' pk=group.id %}'"
value="Староста"> 
{% endif %}
<!---------->
{%if students_list.count > 1 and student.id != headman_id %}
<div style=" padding-left: 3px">
<input type="button"
name="Удалить" 
class="btn btn-inverse btn-small"
onclick="location.href='{% url 'del_student' pk_student=student.id pk_group_del=group.id %}'"
value="Удалить">
</div>
{%endif%}
<!---------->
{%if students_list.count == 1 and group_all.count != 1 %}
<input type="button"
name="Удалить старосту и всю группу" 
class="btn btn-warning btn-small"
onclick="location.href='{% url 'del_group' pk_group=group.id %}'"
value="Удалить старосту и всю группу">
{%endif%}
<!---------->
{%if students_list.count == 1 and group_all.count == 1 %}
Староста
{%endif%}
<!-------------------------------->
</td>

</tr>
{% endfor %}
</table>
<!-------------------------->
<br>
<div align="left" >
<h5>

{%if students_list.count > 1 %}
Группа без старосты существовать не может.<br>
Переопределите старосту группы перед тем,<br>
как удалить его из картотеки студентов <br>
или отредактировать информацию о нем.  
{%endif%}
<!---------->
{%if students_list.count == 1 and group_all.count != 1  %}
В этой группе всего один человек - староста.<br>
Возможно удалить его из картотеки <br>
вместе со всей группой. 
{%endif%}
<!---------->
{%if students_list.count == 1 and group_all.count == 1 %}
В этой группе всего один человек - староста.<br>
Кроме того, это единственная группа в картотеке.<br>
Поэтому невозможно удалить этого студента,<br>
поскольку в ином случае картотека будет полностью закрыта.  
{%endif%}
</h5>
</div>
<!-------------------------->
</div>

{% endblock %}